{% set name = "parsedatetime" %}
{% set version = "2.5" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "d2e9ddb1e463de871d32088a3f3cea3dc8282b1b2800e081bd0ef86900451667" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - pytest-runner

  run:
    - python

test:
  imports:
    - parsedatetime
    - parsedatetime.pdt_locales

about:
  home: https://github.com/bear/parsedatetime
  license_file: LICENSE.txt
  license: Apache 2.0
  license_family: Apache
  summary: 'Parse human-readable date/time text.'
  dev_url: https://github.com/bear/parsedatetime
  doc_url: https://bear.im/code/parsedatetime/docs/index.html

extra:
  recipe-maintainers:
    - pmlandwehr
